### ISSUE TITLE
Projet 1 : LiteChat (positionnement)

### ISSUE THREAD

**Issue by mdevoldere** [mdevoldere/CDA_2005_Bip#3]
Répondez à ce message si vous souhaitez participer à ce projet (1 projet par stagiaire)

**Comment by KawaRoro** [comment]
Je souhaite participer à ce projet ;)

**Comment by LaetitiaCR** [comment]
Je veux bien participer à ce projet.

**Comment by mdevoldere** [comment]
All in One
