### ISSUE TITLE
LiteChat : Créer le projet ASP.NET Core 5.0

### ISSUE THREAD

**Issue by mdevoldere** [mdevoldere/CDA_2005_Bip#5]
Créer le projet ASP.NET Core 5.0 dans le répertoire "LiteChat" du dépôt

Nom du projet : LiteChat

Checklist : 

- [x] Entity Framework SqlServer est installé pour le projet
- [x] Le contrôleur par défaut (HomeController) est créé
- [x] Les dossiers wwwroot, Controllers, Models et Views sont créés
- [x] Le fichier Views/_ViewStart.cshtml est créé
- [x] Le fichier Views/Shared/_Layout.cshtml est créé
- [x] Le fichier Views/Home/Index.cshtml est créé
- [x] Le modèle "User" est créé

Une fois le tout terminé, créer un "pull-request" de votre travail vers la branche "Develop".

**Comment by JJeanniard** [comment]
+1
